name: Testing with unit tests

on:
  - push
  - pull_request

jobs:
  run-unit-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: ["1.10.15", "2.10.7", "2.11.2", "3.0.1"]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-test
      with:
        tarantool-version: ${{matrix.version}}
    - name: build lib
      run: tt rocks make connection-dev-1.rockspec
    - name: run tests
      run: .rocks/bin/luatest --no-capture -v
